name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build Base:
    runs-on: ubuntu-latest
    steps:
    - name: Use Nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
          command: build
          args: --verbose

  Build All Features:    
    runs-on: ubuntu-latest
    steps:
    - name: Use Nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
          command: build
          args: --verbose --all-features

  Test Base:
    runs-on: ubuntu-latest
    steps:
    - name: Use Nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Test
      uses: actions-rs/cargo@v1
      with:
          command: test
          args: --verbose
      
  Test All Features:
    runs-on: ubuntu-latest
    steps:
    - name: Use Nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Test
      uses: actions-rs/cargo@v1
      with:
          command: test
          args: --verbose --all-features

  Coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Use Nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Install Coverage Tooling
      uses: actions-rs/cargo@v1
      with:
          command: install
          args: cargo-tarpaulin
    - name: Run Coverage
      uses: actions-rs/cargo@v1
      with:
          command: tarpaulin
          args: -v --out Xml
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
          fail_ci_if_error: true
    
  Format:
    runs-on: ubuntu-latest
    steps:
    - name: Use Nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: rustfmt
          override: true
    - name: Check
      uses: actions-rs/cargo@v1
      with:
          command: fmt
          args: --all -- --check

  Clippy:
    runs-on: ubuntu-latest 
    steps:
    - name: Use Nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: clippy
          override: true
    - name: Check 
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

